# Generated by Django 5.1.6 on 2025-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_hotel_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages/'),
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transport/'),
        ),
    ]
